import type { AuthUser } from "#/auth";
import type { BookingManifestItem, Order, OrderListItem } from "./types";

export const bookingInUsd: BookingManifestItem = {
	id: "bk-1",
	position: 1,
	reference: "#1001-1",
	context: "bookings",
	orderId: "ord-1",
	currency: "USD",
	customer: {
		name: "Ada",
		email: "ada@example.com",
		phone: null,
		detail: null,
	},
	slotId: "slot-1",
	experienceId: "exp-1",
	experienceName: "Buggies",
	startAt: "2026-10-09T09:00:00",
	endAt: "2026-10-09T13:00:00",
	pickup: null,
	partySize: 2,
	totalPrice: 338,
	status: "CONFIRMED",
	cancellation: null,
	lines: [
		{
			id: "ln-1",
			audienceId: "a",
			audienceName: "Adult",
			quantity: 2,
			unitPrice: 169,
			pickupUnitPrice: 0,
		},
	],
};

export const operatorInEur: AuthUser = {
	id: "u-1",
	context: "users",
	name: "Ada",
	avatarUrl: null,
	language: "en",
	tourOperators: [
		{
			id: "op-1",
			name: "Scape Park",
			logoUrl: null,
			timezone: "America/Santo_Domingo",
			currency: "EUR",
			isDefault: true,
			role: "OWNER",
		},
	],
};

export const orderInUsd: Order = {
	id: "ord-1",
	number: 1001,
	reference: "#1001",
	context: "orders",
	status: "CONFIRMED",
	paymentState: "PARTIALLY_REFUNDED",
	refundedTotal: 40,
	refunds: [
		{
			id: "rf-1",
			bookingId: "bk-1",
			amount: 40,
			currency: "USD",
			status: "SUCCEEDED",
			reason: "Rained out",
			requestedBy: "u-1",
			createdAt: "2026-10-02T15:00:00Z",
		},
		{
			id: "rf-2",
			bookingId: "bk-1",
			amount: 10,
			currency: "USD",
			status: "FAILED",
			reason: null,
			requestedBy: "u-1",
			createdAt: "2026-10-03T09:30:00Z",
		},
		{
			id: "rf-3",
			bookingId: "bk-2",
			amount: 15,
			currency: "USD",
			status: "PENDING",
			reason: null,
			requestedBy: "u-1",
			createdAt: "2026-10-04T08:00:00Z",
		},
	],
	checkoutSessionId: "cs-1",
	paymentId: "pi_123",
	customer: {
		name: "Ada",
		email: "ada@example.com",
		phone: null,
		detail: null,
	},
	totalPrice: 338,
	fees: {
		linesTotal: 338,
		bookingFee: 16.9,
		bookingFeePercentage: 5,
		bookingFeeBearer: "OPERATOR",
		operatorAmount: 321.1,
	},
	currency: "USD",
	placedAt: "2026-10-01T12:00:00Z",
	bookings: [
		bookingInUsd,
		{ ...bookingInUsd, id: "bk-2", position: 2, reference: "#1001-2" },
	],
};

export const orderRowInUsd: OrderListItem = {
	id: orderInUsd.id,
	number: orderInUsd.number,
	reference: orderInUsd.reference,
	context: "orders",
	status: orderInUsd.status,
	paymentState: orderInUsd.paymentState,
	refundedTotal: orderInUsd.refundedTotal,
	customerName: orderInUsd.customer.name,
	customerEmail: orderInUsd.customer.email,
	totalPrice: orderInUsd.totalPrice,
	fees: orderInUsd.fees,
	currency: orderInUsd.currency,
	placedAt: orderInUsd.placedAt,
};
